# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pyinstaller

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover tests
        coverage report > coverage.txt

    - name: Upload coverage.txt to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add coverage.txt
        git commit -m "Add coverage report [CI]" || echo "No changes to commit"
        git push origin main || echo "Push skipped on PR"

    - name: Build .exe using PyInstaller
      run: pyinstaller --onefile main.py

    - name: Upload .exe
      uses: actions/upload-artifact@v3
      with:
        name: main-executable
        path: dist/main.exe

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.txt
