name: Python Linux Build and Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements"
        pip install coverage pyinstaller

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover tests
        coverage report > coverage.txt

    - name: Clean previous build
      run: |
        rm -rf build dist __pycache__ main.spec || echo "Nothing to clean"
        echo "Cleaned"

    - name: Build Linux binary with PyInstaller
      run: pyinstaller --onefile main.py

    - name: Create GitHub Release
      id: create_release
      if: github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Linux binary to GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/main
        asset_name: main-linux
        asset_content_type: application/octet-stream
